### PR TITLE
Update hveto to use gwtrigfind

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR updates `hveto` to use [`gwtrigfind`](//pypi.org/project/gwtrigfind), instead of the old `trigfind` module (which was never packaged properly).

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
This PR needs gwdetchar/gwdetchar#97 to be merged first.

**Comment by duncanmmacleod** [comment]
this is now exhibiting an actual failure

**Comment by alurban** [comment]
@duncanmacleod @jrsmith02, gwdetchar/gwdetchar:#97 has been merged (just FYI)

**Comment by alurban** [comment]
@duncanmmacleod, if you're happy with this PR, can you merge? (I don't seem to have merge permissions in this repo.)

**Pull request merged**
